
FROM spellrun/tensorflow-cpu:latest

LABEL maintainer "wmx <418475102@qq.com>"

RUN pip install bert-serving-server
COPY ./ /app
COPY entrypoint.sh /app
WORKDIR /app
ENTRYPOINT ["/app/entrypoint.sh"]
CMD []
