ARG TF_VERSION=1.12.0-py3

FROM tensorflow/tensorflow:${TF_VERSION}

LABEL maintainer "wmx <418475102@qq.com>"

ENV REFRESHED_AT 2019-11-21

# Install basic dependencies
RUN apt-get -yqq update && apt-get install -qqy --no-install-recommends \
        htop \
        tmux \
        vim \
        curl \
        net-tools \
        git-core \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY .bashrc /root/

# install Anaconda3
RUN curl -O https://repo.continuum.io/archive/Anaconda3-2018.12-Linux-x86_64.sh \
    && bash Anaconda3-2018.12-Linux-x86_64.sh -b \
    && rm Anaconda3-2018.12-Linux-x86_64.sh

ENV PATH /root/anaconda3/bin:$PATH

# Configure Anaconda3 environment
RUN conda create -n jupyter pip python=3.6.6 \
    && echo "source activate jupyter" >> ~/.bashrc

ENV PATH /root/anaconda3/envs/jupyter/bin:$PATH


CMD []

#CMD ["/bin/sh", "-c", "which python && jupyter notebook --allow-root"]
